### ISSUE TITLE
Cannot convert null value to Q42.HueApi.Models.Groups.GroupType.

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#106]
Looks like, with older firmware versions, the GroupType is not visible or is null, resulting this error:

> Cannot convert null value to Q42.HueApi.Models.Groups.GroupType. Path '[0].type', line 1, position 35. - -2146233088
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(Json.JsonReader reader, Type objectType, Object existingValue, Json.JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(Json.JsonConverter converter, Json.JsonReader reader, Type objectType, Object existingValue)

**Comment by michielpost** [comment]
GroupType is now nullable. Released in NuGet package 3.3.3
