### ISSUE TITLE
NullReferenceException occurred (v 3.4.1 new properties for Bridge)

### ISSUE THREAD

**Issue by Rep-Hueman** [Q42/Q42.HueApi#112]
line 40:     _conv = await _client.GetBridgeAsync();

System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Q42.HueApi.HueClient.DeserializeResult[T](String json)
   at Q42.HueApi.HueClient.<GetBridgeAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HueMan.Views.Configuratie.<InitializeHue>d__5.MoveNext() in C:\Data\Projecten\HueMan\HueMan\Views\Configuratie.xaml.cs:line 40

**Comment by michielpost** [comment]
Can you supply the incoming json?

**Comment by Rep-Hueman** [comment]
[incomming-json.txt](https://github.com/Q42/Q42.HueApi/files/1002096/incomming-json.txt)

**Comment by Rep-Hueman** [comment]
can you see the problem?

old:
[DataMember(Name = "internetservices")]
 public string InternetServices { get; set; }

new:
[DataMember(Name = "internetservices")]
   public InternetServices InternetServices { get; set; }

extra file:
[Internetservices.cs.txt](https://github.com/Q42/Q42.HueApi/files/1007509/Internetservices.cs.txt)

**Comment by michielpost** [comment]
Thanks, fixed in version 3.4.2, now on NuGet
