### ISSUE TITLE
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by punthoofd07** [Q42/Q42.HueApi#194]
Hi, 

I'm using the library to read out some motion sensors I bought. It works, but when doing this in a while loop I receive the following error after some reads: 

Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Q42.HueApi.HueClient.GetLightsAsync()
   at SGW_Blazor.Services.HomeReceiverHostedService.ExecuteAsync(CancellationToken cancellationToken) in C:\Users\marni\source\repos\HueSensorTest\HueSensorTest\Services\HomeReceiverHostedService.cs:line 92

```
while (state == open)
                    {
                        motionSensor = await hueClient.GetSensorAsync("5");
                        ambientSensor = await hueClient.GetSensorAsync("6");
                        temperatureSensor = await hueClient.GetSensorAsync("7");
                        await Task.Delay(100);

                        // do stuff when it gets dark or motion is detected
                    }
```

Using .Net Core 3.0 MVC Web App.

Thanks

**Comment by punthoofd07** [comment]
I managed to trace the communication with Wireshark and found out that on every request I sent, I also get a reply from the bridge, but it looks like the HttpClient times out for some reason. It's pretty random

**Comment by michielpost** [comment]
This sounds like a case of HttpClient socket exhaustion. See for example:
https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/
https://stackoverflow.com/questions/39733371/why-does-httpclient-leave-sockets-open

When you create a new LocalHueClient, you can supply your own HttpClient in the constructor and reuse existing HttpClients, see:
https://github.com/Q42/Q42.HueApi/blob/master/src/Q42.HueApi/LocalHueClient.cs#L68

That might help fix it.

**Comment by punthoofd07** [comment]
Thanks for your suggestion. I tried it like this: 
`HttpClient hueHttpClient = new HttpClient();
hueHttpClient.Timeout = new TimeSpan(0, 0, 5);
hueClient = new LocalHueClient("10.1.1.136", hueHttpClient);`

This code is outside the while loop by the way. 

but I'm still getting the errors (this time I get them faster because I decreased the timeout). 

Also; sometimes I receive the following error: 

Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Q42.HueApi.HueClient.GetSensorAsync(String id)
   at SGW_Blazor.Services.HomeReceiverHostedService.ExecuteAsync(CancellationToken cancellationToken) in C:\Users\marni\source\repos\HueSensorTest\HueSensorTest\Services\HomeReceiverHostedService.cs:line 95

**Comment by michielpost** [comment]
My suggestion is to make less http calls.
You're doing 3 http calls in a while loop with a 100ms wait. So that's 30 http calls every seconds. That's causing the trouble. You can get a larger server, it will then take more time before you will have this problem. 
Is is really needed to do 30 http calls a second? Maybe do a 1000ms delay, so it will be 3 http calls a second. 

Are you running this from a Blazor frontend app? Or is the server running this code?
I'm not sure what the limitations of Blazor are, but that's also something to look into.

**Comment by punthoofd07** [comment]
Thanks for your suggestions. However I already tried to set it on 400ms after each getsensorasync() as well. reading out 3 sensors at once takes between 4-12ms (checked that with a stopwatch). 

It's reading out a sensor, so setting the loop to 1000ms is really the maximum, otherwise it's not 'real-time' anymore. Now I'm just testing with 1 motion sensor (includes also ambient and temperature, so 3 in total), but I'm willing to add more as well. Based on the motion something needs to be triggered. 
Meaning that the number of http calls will increase even more. 

What do you mean by this: "You can get a larger server, it will then take more time before you will have this problem."? I'm testing the application on my desktop computer (all wired). 

I was running it in Blazor, but as a test I also created a .net core MVC 3.0 and 2.2 version. All the same result. This is a clean project in 3.0 (no blazor), running directly from a 'server'. No frontend running this code. 

I also tried to implement an IHttpClientFactory [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0](url). It generates the same result however. 

For now I can circumvent it by adding an Httpclient to the constructor and set the timeout to 1000ms in combination with the IHttpClientFactory (which created a new http client). 

Other suggestions still welcome because this workaround is not a best practice. :-)

**Comment by michielpost** [comment]
A server with more CPU power / RAM has more sockets to use I believe.

But I think this is not a problem with the Q42.HueApi library. You should test it with just plain http calls to the sensor api using the HttpClient, you will probably run into the same problem.

**Comment by punthoofd07** [comment]
I think a simple i7-4770K with 16GB is enough power to run some simple http API calls. ;-) 
I'll try your last suggestion as well though. 

Is there a way to use another HttpClient library with Q42.HueApi? Because what I read on the internet regarding this MS library... does not come with lots of good news.

**Comment by michielpost** [comment]
The Q42.HueApi only works with the default HttpClient

**Comment by punthoofd07** [comment]
I would like to mention that I don't have this issue in winforms. 
I create a receiver thread with the exact same code, and there I don't have any issue.
